<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Author.aspx.cs" Inherits="LMS3.Author" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <asp:Label ID="Label1" runat="server" Text="Author: "></asp:Label>
            <asp:TextBox ID="txtAuthor" runat="server"></asp:TextBox>
        </div>
        <div>
            <asp:Label ID="Label2" runat="server" Text="Gender: "></asp:Label>
            <asp:TextBox ID="txtGender" runat="server"></asp:TextBox>
        </div>
        <div>
            <asp:Label ID="Label3" runat="server" Text="Qualification: "></asp:Label>
            <asp:TextBox ID="txtQualification" runat="server"></asp:TextBox>
        </div>
        <asp:Button ID="bthInsert" runat="server" Text="Insert" OnClick="bthInsert_Click" />
        <asp:GridView ID="GridView1" runat="server" DataKeyNames="ID" OnRowDataBound="OnRowDataBound" OnRowEditing="OnRowEditing" OnRowCancelingEdit="OnRowCancelingEdit" OnRowUpdating="OnRowUpdating" OnRowDeleting="OnRowDeleting" EmptyDataText="No records has been added." AutoGenerateEditButton="true" AutoGenerateDeleteButton="true"></asp:GridView>
    </form>
    
</body>
</html>
